import type { FeatureFlagDefinition } from './types';

export const FEATURE_FLAGS = [
  {
    key: 'feature.swipe_v2',
    kind: 'feature',
    description: 'Experimental swipe deck interaction model.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['experiment'],
    studioOnly: false,
  },
  {
    key: 'ai.profile_assist',
    kind: 'feature',
    description: 'AI-assisted profile improvement for discovery quality.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai'],
    studioOnly: false,
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.match_quality_scoring',
    kind: 'feature',
    description: 'Re-rank discovery feed by AI-predicted match quality.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai'],
    studioOnly: false,
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.safety_classifier',
    kind: 'feature',
    description: 'Classify inbound messages and escalate unsafe content.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai'],
    studioOnly: false,
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'compliance.gdpr_strict',
    kind: 'feature',
    description: 'Stricter consent banners, export flows, and retention hints.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['compliance'],
    studioOnly: false,
  },
  {
    key: 'feature.dark_mode',
    kind: 'feature',
    description: 'Allow tenant-branded dark appearance in client apps.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['brand'],
    studioOnly: false,
  },
  {
    key: 'feature.export_csv',
    kind: 'feature',
    description: 'Allow workspace admins to export tabular data as CSV.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: [] as string[],
    studioOnly: false,
  },
] as const satisfies readonly FeatureFlagDefinition[];
