import type { FeatureFlagDefinition } from './types';

export const FEATURE_FLAGS = [
  {
    key: 'feature.swipe_v2',
    kind: 'feature',
    description: 'Experimental swipe deck interaction model.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['experiment'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.profile_assist',
    kind: 'feature',
    description: 'AI-assisted profile improvement for discovery quality.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai', 'public'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.match_quality_scoring',
    kind: 'feature',
    description: 'Re-rank discovery feed by AI-predicted match quality.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai', 'public'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.safety_classifier',
    kind: 'feature',
    description: 'Classify inbound messages and escalate unsafe content.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai', 'public'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'compliance.gdpr_strict',
    kind: 'feature',
    description: 'Stricter consent banners, export flows, and retention hints.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['compliance'],
    studioOnly: false,
    lifecycle: 'stable',
  },
  {
    key: 'feature.dark_mode',
    kind: 'feature',
    description: 'Allow tenant-branded dark appearance in client apps.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['brand'],
    studioOnly: false,
    lifecycle: 'stable',
  },
  {
    key: 'feature.premium_upsell',
    kind: 'feature',
    description: 'Show paid-plan upgrade CTAs in the end-user app (sidebar, paywalls, etc.).',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['monetization', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.discover_show_distance',
    kind: 'feature',
    description: 'Show approximate distance on discover cards. Disable to dogfood privacy-first UI.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['privacy', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.mobile_skeleton_loading',
    kind: 'feature',
    description: 'Show shimmering skeleton placeholders while the discover feed is loading on mobile.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['experience', 'public'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.mobile_press_animations',
    kind: 'feature',
    description: 'Press-in scale feedback on primary action buttons in the mobile dating app.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['experience', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.export_csv',
    kind: 'feature',
    description: 'Allow workspace admins to export tabular data as CSV.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: [] as string[],
    studioOnly: false,
    lifecycle: 'stable',
  },
  {
    key: 'program.intentional_dating',
    kind: 'feature',
    description: 'Intentional-dating program: prompts-forward copy and paced discover defaults.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['public', 'program'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'program.city_launch',
    kind: 'feature',
    description: 'City-launch program: geo-scoped positioning and growth surfaces.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'program'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'program.premium_vetted',
    kind: 'feature',
    description: 'Premium / vetted program: verification and elevated trust posture.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'program'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.discover_filters',
    kind: 'feature',
    description: 'Advanced discover filters (age, distance, gender) applied in the feed API.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'discover'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_rewind',
    kind: 'feature',
    description: 'Undo last swipe (Plus entitlement still required for members).',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'discover'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_invite_waitlist',
    kind: 'feature',
    description: 'Invite-only / waitlist surfaces for city-launch programs.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'growth'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_block_user',
    kind: 'feature',
    description: 'Block user from discover and messaging.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'trust'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_report_surfaces',
    kind: 'feature',
    description: 'Report from profile and discover (not only chat).',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'trust'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_photo_moderation',
    kind: 'feature',
    description: 'Photo moderation queue and status on uploads.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['trust'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_photo_upload',
    kind: 'feature',
    description: 'Signed Storage uploads for profile photos (not mock URLs).',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'trust'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_stripe_live',
    kind: 'feature',
    description: 'Use live Stripe checkout instead of mock-only billing.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['monetization'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_revenuecat',
    kind: 'feature',
    description: 'RevenueCat in-app purchase entitlements on mobile.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['monetization', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_native_chat',
    kind: 'feature',
    description: 'In-app chat threads on Expo (native launch pack).',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'mobile'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_native_onboarding',
    kind: 'feature',
    description: 'Full onboarding flow on mobile.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'mobile'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_native_premium',
    kind: 'feature',
    description: 'Premium paywall and checkout on mobile.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'mobile', 'monetization'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_push_notifications',
    kind: 'feature',
    description: 'Push notifications for matches and messages.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'growth'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.dating_realtime_chat',
    kind: 'feature',
    description: 'Supabase Realtime delivery on chat threads.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'growth'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
] as const satisfies readonly FeatureFlagDefinition[];
