import type { FeatureFlagDefinition } from './types';

export const FEATURE_FLAGS = [
  {
    key: 'feature.swipe_v2',
    kind: 'feature',
    description: 'Experimental swipe deck interaction model.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['experiment'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.profile_assist',
    kind: 'feature',
    description: 'AI-assisted profile improvement for discovery quality.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.match_quality_scoring',
    kind: 'feature',
    description: 'Re-rank discovery feed by AI-predicted match quality.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'ai.safety_classifier',
    kind: 'feature',
    description: 'Classify inbound messages and escalate unsafe content.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['ai'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'compliance.gdpr_strict',
    kind: 'feature',
    description: 'Stricter consent banners, export flows, and retention hints.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['compliance'],
    studioOnly: false,
    lifecycle: 'stable',
  },
  {
    key: 'feature.dark_mode',
    kind: 'feature',
    description: 'Allow tenant-branded dark appearance in client apps.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['brand'],
    studioOnly: false,
    lifecycle: 'stable',
  },
  {
    key: 'feature.premium_upsell',
    kind: 'feature',
    description: 'Show paid-plan upgrade CTAs in the end-user app (sidebar, paywalls, etc.).',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['monetization', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.discover_show_distance',
    kind: 'feature',
    description: 'Show approximate distance on discover cards. Disable to dogfood privacy-first UI.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['privacy', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.mobile_skeleton_loading',
    kind: 'feature',
    description: 'Show shimmering skeleton placeholders while the discover feed is loading on mobile.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['experience', 'public'],
    studioOnly: false,
    lifecycle: 'experimental',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.mobile_press_animations',
    kind: 'feature',
    description: 'Press-in scale feedback on primary action buttons in the mobile dating app.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['experience', 'public'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.export_csv',
    kind: 'feature',
    description: 'Allow workspace admins to export tabular data as CSV.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: [] as string[],
    studioOnly: false,
    lifecycle: 'stable',
  },
  {
    key: 'feature.mobile_press_animations',
    kind: 'feature',
    description: 'Subtle press feedback on primary CTAs in the mobile dating shell.',
    scope: 'tenant',
    defaultEnabled: true,
    tags: ['public', 'experience'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
  {
    key: 'feature.mobile_skeleton_loading',
    kind: 'feature',
    description: 'Branded skeleton placeholders instead of a centered spinner while discover loads.',
    scope: 'tenant',
    defaultEnabled: false,
    tags: ['public', 'experience'],
    studioOnly: false,
    lifecycle: 'stable',
    blueprintKinds: ['social_matching'],
  },
] as const satisfies readonly FeatureFlagDefinition[];
